language: go

go:
- '1.11'

env:
- GO111MODULE=on

install:
- go get -u github.com/alecthomas/gometalinter
- gometalinter --install
- go get github.com/mattn/goveralls

services:
- postgresql

before_script:
- psql -U postgres -c "ALTER ROLE postgres WITH PASSWORD 'postgres';"

script:
- go mod vendor -v
- GO111MODULE=off gometalinter --config=.gometalinter.json --deadline=10m .
- go test -mod=readonly -v -tags=integration -coverprofile=profile.cov ./...

after_success:
- goveralls -coverprofile=profile.cov -service=travis-ci
